### ISSUE TITLE
netdaemon warning in supervisor log

### ISSUE THREAD

**Issue by jumping2000** [helto4real/hassio-add-ons#18] opened 2020-02-17 10:06 UTC
I have installed only "a better presence" addon and I have this warning related to netdaemon in my supervisor log, could you verify? thanks

20-02-17 03:26:55 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/1e72b768/netdaemon/netdaemon/config.json: required key not provided @ data['arch']. Got None
required key not provided @ data['boot']. Got None
required key not provided @ data['description']. Got None
required key not provided @ data['name']. Got None
required key not provided @ data['options']. Got None
required key not provided @ data['schema']. Got None
required key not provided @ data['slug']. Got None
required key not provided @ data['startup']. Got None
required key not provided @ data['version']. Got None

**Comment by raffaelevall** [comment] 2020-02-18 11:59
Hi dear,
I have the same warning:

20-02-18 11:57:28 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/1e72b768/netdaemon/netdaemon/config.json: required key not provided @ data['arch']. Got None
required key not provided @ data['boot']. Got None
required key not provided @ data['description']. Got None
required key not provided @ data['name']. Got None
required key not provided @ data['options']. Got None
required key not provided @ data['schema']. Got None
required key not provided @ data['slug']. Got None
required key not provided @ data['startup']. Got None
required key not provided @ data['version']. Got None

Tks a lot
Raffaele

**Comment by helto4real** [comment] 2020-03-07 17:24
@raffaelevall  and @jumping2000  you still have problems with this?

**Comment by raffaelevall** [comment] 2020-03-07 17:27
Yes, my friend, 😬

**Comment by helto4real** [comment] 2020-03-07 17:29
I can reproduce this. I will check it out. I assume everything works as expected anyway?  @raffaelevall

**Comment by raffaelevall** [comment] 2020-03-07 18:00
Ok, many tks, everything works, but this warning is in the supervisor log.

**Comment by helto4real** [comment] 2020-03-07 19:28
Think I found the issue.. Try to uninstall and install the plugin. Do a refresh first with in the add-on store. Remember to save your settings first though

**Comment by raffaelevall** [comment] 2020-03-07 20:25
Ok, I try as soon as possible, tks

**Comment by raffaelevall** [comment] 2020-03-08 21:35
Hi Tomas, at the moment I have no warning in the log, without uninstall the addon.
If come back I try to do as you said. 
Thank you

**Comment by helto4real** [comment] 2020-03-08 21:43
@raffaelevall  thank you for reporting back to me. I think I can close this since I beleive I solved the problem. Just reopen if it will come back.

**Closed by helto4real** 2020-03-08 21:43 UTC
